
/* -------------------------------------------------------------------
   Code generated by SAS Task

   Generated on: Wednesday, January 07, 2015 at 2:38:19 PM
   By task: VarriablesAdult01.07.15

   Input Data: Local:NATDATA.NATVARRIABLESADULTS01.07.15
   Server:  Local
   ------------------------------------------------------------------- */

%_eg_conditional_dropds(WORK.CONTContentsForNATVARRIABLESADUL);
TITLE "Data set attributes for sub set data" ;
FOOTNOTE;
FOOTNOTE1 "Generated by the SAS System (&_SASSERVERNAME, &SYSSCPL) on %TRIM(%QSYSFUNC(DATE(), NLDATE20.)) at %TRIM(%SYSFUNC(TIME(), TIMEAMPM12.))";

PROC DATASETS NOLIST NODETAILS; 
   CONTENTS DATA=NATDATA.'NATVARRIABLESADULTS01.07.15'n ;

RUN;



